/**
 * Writes public/sitemap.xml and public/robots.txt.
 * Dữ liệu bài verified: import từ src/data/appData.ts (một nguồn).
 */
import { mkdirSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

import { MOCK_LECTURES } from '../src/data/appData'

const __dirname = dirname(fileURLToPath(import.meta.url))
const publicDir = join(__dirname, '..', 'public')

const siteUrl = (process.env.VITE_SITE_URL || 'https://example.com').replace(/\/$/, '')

type SitemapEntry = { loc: string; changefreq: string; priority: string }

const verifiedLectureRoutes: SitemapEntry[] = MOCK_LECTURES.filter((l) => l.is_verified === true).map(
  (l) => ({
    loc: `/workspace?lecture=${encodeURIComponent(l.id)}`,
    changefreq: 'weekly',
    priority: '0.92',
  }),
)

const MAIN_ROUTES: SitemapEntry[] = [
  { loc: '/', changefreq: 'daily', priority: '1.0' },
  { loc: '/dashboard', changefreq: 'daily', priority: '0.9' },
  { loc: '/workspace', changefreq: 'weekly', priority: '0.95' },
  { loc: '/quiz', changefreq: 'weekly', priority: '0.85' },
  { loc: '/analytics', changefreq: 'weekly', priority: '0.7' },
  { loc: '/settings', changefreq: 'monthly', priority: '0.5' },
]

const ROUTES: SitemapEntry[] = [...MAIN_ROUTES, ...verifiedLectureRoutes]

const lastmod = new Date().toISOString().split('T')[0]

function locXml(loc: string) {
  const path = loc === '/' ? '/' : loc
  return `${siteUrl}${path}`
}

const urlset = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${ROUTES.map(
  ({ loc, changefreq, priority }) => `  <url>
    <loc>${locXml(loc)}</loc>
    <lastmod>${lastmod}</lastmod>
    <changefreq>${changefreq}</changefreq>
    <priority>${priority}</priority>
  </url>`,
).join('\n')}
</urlset>
`

const robots = `# Auto-generated by scripts/generate-seo-files.ts (npm run seo:generate)
# Default policy: full public SPA (citation-friendly)
User-agent: *
Allow: /

# AI / LLM crawlers — explicit Allow (same as *; documents intent for training & citation)
User-agent: GPTBot
Allow: /

User-agent: ChatGPT-User
Allow: /

User-agent: OAI-SearchBot
Allow: /

User-agent: Google-Extended
Allow: /

User-agent: Googlebot
Allow: /

User-agent: ClaudeBot
Allow: /

User-agent: anthropic-ai
Allow: /

User-agent: Claude-Web
Allow: /

User-agent: PerplexityBot
Allow: /

User-agent: Bytespider
Allow: /

User-agent: CCBot
Allow: /

Sitemap: ${siteUrl}/sitemap.xml
`

mkdirSync(publicDir, { recursive: true })
writeFileSync(join(publicDir, 'sitemap.xml'), urlset, 'utf8')
writeFileSync(join(publicDir, 'robots.txt'), robots, 'utf8')

console.log(`SEO files written for base URL: ${siteUrl}`)
console.log(`  → ${join(publicDir, 'sitemap.xml')} (${ROUTES.length} URLs, ${verifiedLectureRoutes.length} verified lectures)`)
console.log(`  → ${join(publicDir, 'robots.txt')}`)
