/**
 * Ether / Intelligent Ether — shared Tailwind theme (single source of truth).
 * Aligns with synthetix_ui/DESIGN.md and legacy prototype tokens.
 */
module.exports = {
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'secondary-fixed': '#d9dff5',
        'surface-container-lowest': '#ffffff',
        'primary-fixed': '#ae8dff',
        'on-secondary-fixed': '#373d4e',
        'primary-container': '#ae8dff',
        tertiary: '#9d365b',
        'on-tertiary-fixed': '#380018',
        surface: '#f5f6f7',
        'on-error': '#ffefef',
        'tertiary-dim': '#8e294f',
        'tertiary-fixed-dim': '#f67ca3',
        'surface-container-low': '#eff1f2',
        'secondary-fixed-dim': '#cbd1e6',
        'on-primary-container': '#2b006e',
        'primary-fixed-dim': '#a27cff',
        'on-error-container': '#510017',
        'on-secondary-fixed-variant': '#535a6b',
        'inverse-surface': '#0c0f10',
        'surface-container-high': '#e0e3e4',
        'on-primary-fixed-variant': '#370086',
        'surface-tint': '#6a37d4',
        'surface-container': '#e6e8ea',
        'secondary-dim': '#494f61',
        'on-tertiary': '#ffeff1',
        'on-background': '#2c2f30',
        'error-container': '#f74b6d',
        'on-surface': '#2c2f30',
        'tertiary-container': '#ff8eb0',
        'surface-container-highest': '#dadddf',
        'secondary-container': '#d9dff5',
        'surface-bright': '#f5f6f7',
        'inverse-on-surface': '#9b9d9e',
        'surface-dim': '#d1d5d7',
        primary: '#6a37d4',
        'on-secondary-container': '#495061',
        'surface-variant': '#dadddf',
        'tertiary-fixed': '#ff8eb0',
        'outline-variant': '#abadae',
        outline: '#757778',
        'error-dim': '#a70138',
        'on-secondary': '#f0f2ff',
        'on-primary-fixed': '#000000',
        'on-tertiary-container': '#640430',
        'on-primary': '#f8f0ff',
        background: '#f5f6f7',
        error: '#b41340',
        'on-tertiary-fixed-variant': '#701039',
        'on-surface-variant': '#595c5d',
        'inverse-primary': '#a078ff',
        secondary: '#545b6d',
        'primary-dim': '#5e26c7',
      },
      fontFamily: {
        headline: ['Inter', 'system-ui', 'sans-serif'],
        body: ['Inter', 'system-ui', 'sans-serif'],
        label: ['Inter', 'system-ui', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      keyframes: {
        'bounce-subtle': {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-4px)' },
        },
        pulse: {
          '0%': { boxShadow: '0 0 0 0 rgba(106, 55, 212, 0.4)' },
          '70%': { boxShadow: '0 0 0 10px rgba(106, 55, 212, 0)' },
          '100%': { boxShadow: '0 0 0 0 rgba(106, 55, 212, 0)' },
        },
      },
      animation: {
        'bounce-subtle': 'bounce-subtle 2s ease-in-out infinite',
        pulse: 'pulse 2s infinite',
      },
      boxShadow: {
        ambient: '0 20px 40px rgba(106, 55, 212, 0.08)',
      },
    },
  },
};
